gpg-key: 7D98B067FFEFDAA5F8941D4CDFA98DBF970012EE
sdk-version: master
apps:
- name: io.liri.Calculator
  tag: develop
  version: master
- name: io.liri.Text
  tag: develop
  version: master
- name: io.liri.Browser
  tag: develop
  version: master
- name: io.liri.Files
  tag: develop
  version: master
