#!/usr/bin/env python3
#
# This file is part of Liri.
#
# Copyright (C) 2017 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# $BEGIN_LICENSE:GPL3+$
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $END_LICENSE$
#

import os
import argparse
import yaml
from builder import command, prepare

URL = 'liri@liri.io:/srv/www/repo.liri.io/flatpak'


def copy_flatpakref(metadata):
    """
    Create and copy flatpakref files to the Liri site.
    :param metadata: App metadata.
    """
    flatpakref_filename = metadata['name'] + '.flatpakref'
    prepare('{}.flatpakref.in'.format(metadata['name']), flatpakref_filename, metadata)
    command(['scp', flatpakref_filename, URL])
    os.unlink(flatpakref_filename)


if __name__ == '__main__':
    import copy

    # Parse command line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('--repo', help='OSTree repository',
                        action='store', default='repo')
    args = parser.parse_args()

    # Copy flatpakref files and rsync OSTree repository
    with open('.metadata.yml', 'r') as f:
        metadata = yaml.load(f)
        for app in metadata['apps']:
            app_metadata = copy.deepcopy(app)
            app_metadata.update({'sdk-version': metadata['sdk-version']})
            copy_flatpakref(app_metadata)
        command(['./rsync-repos', '--src', args.repo + '/', '--dest', os.path.join(URL, 'apps/')], output=True)